datastax/ruby-driver

features/error_handling/request_execution.feature, features/support/env.rb, support/ccm.rb
Refactored `block_node` and `unblock_nodes` in ccm.rb to use the new CCM commands `pause` and `resume`, and dropped the use of the Firewall class. Also refactored the scenario `Connecting to unreachable cluster` with updated error message.
=> [RUBY-30] Jenkins CI fixes

CHANGELOG.md, lib/cassandra/cluster/client.rb, lib/cassandra/cluster/connector.rb, spec/cassandra/cluster/client_spec.rb, spec/support/stub_io_reactor.rb
removed recursive reconnection, schedule partially-connected hosts to fully reconnect in the background, raise error when all hosts are partially-connected
=> [RUBY-93] don't create connections recursively

features/basics/batch_statements.feature, integration/serial_consistency_test.rb
Serial consistency tests for batches, includes integration tests and cucumber features. Also includes integration tests for previously untested serial consistency of simple and prepared statements.
=> [Ruby-114] Serial consistency tests

CHANGELOG.md, lib/cassandra/execution/options.rb, lib/cassandra/protocol/coder.rb, lib/cassandra/session.rb, lib/cassandra/statements/batch.rb, lib/cassandra/statements/simple.rb, spec/cassandra/session_spec.rb
I've been using cql-rb, and in upgrading a project to use ruby-driver instead, noticed that there's no way to do a parameterized query (without preparing it) if the CQL type is `INT` instead of `BIGINT` (because of the way ruby-driver uses `Util.guess_type` to determine the CQL type for `Fixnum`)
This was possible in cql-rb with the `type_hints` option, so I thought I'd port that option over to the datastax driver.
An example (without my changes): 
```ruby
~/oss/test_cql_driver bundle
Resolving dependencies...
Using ione 1.2.1
Using cassandra-driver 2.1.4
Using bundler 1.10.5
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
~/oss/test_cql_driver be irb
irb(main):001:0> require 'cassandra'
=> true …
```
=> adding type_hints for simple statements, to override Util.guess_type

.travis.yml, cucumber.yml
Removed integration tests from Travis, updated Rubies and Cassandra to latest versions. Travis is only running against master, so these changes won't take into effect until 3.0.0b merges into master.
=> Update travis configs

Gemfile, Gemfile.lock, integration/integration_test_case.rb
At the start of each test case print out the test name. This should make it easier to track down where hangs occur.
=> Emit test name

.travis.yml
* For Rubinius, use rbx, not rbx-2.xx
* Add a before_install action that uninstalls whatever bundler(s) are installed on the VM and install the versions we need.
=> Tweak Travis config to work in new Travis infrastructure:

lib/cassandra/protocol/cql_byte_buffer.rb, lib/cassandra/protocol/v3.rb, lib/cassandra/protocol/v4.rb, spec/cassandra/protocol/v3/decoder_spec.rb, spec/cassandra/protocol/v4/decoder_spec.rb
Don't throw out the whole buffer when we see a warning in a frame, since the buffer may contain some/all of the next frame(s).
=> Fixed RUBY-156

lib/cassandra/types.rb
For some reason, Cassandra::Types#new_uuid has the same signature as the assert_#{@kind} methods, rather than the signature for new_#{@kind}.  This causes an error, since no 'message' argument gets passed via Cassandra::Types#new.
=> Correct the signature for Cassandra::Types#new_uuid

lib/cassandra/protocol/cql_protocol_handler.rb, spec/cassandra/protocol/cql_protocol_handler_spec.rb, spec/support/fake_io_reactor.rb
Request timeout should start counting when request is sent; in particular the timer for queued requests shouldn't start until it is sent to the io reactor.
=> Fixed RUBY-155

.travis.yml, build.yaml
Rubies: 
- Dropped: MRI 1.9, 2.0, 2.1, and rbx. 
- Added: Jruby 9k
Cassandra:
- Dropped: 3.1
- Added: 3.3
=> Updating CI runtimes

lib/cassandra/cluster/connector.rb, lib/cassandra/protocol/cql_protocol_handler.rb, spec/cassandra/cluster/client_spec.rb, spec/cassandra/cluster/control_connection_spec.rb, spec/cassandra/cluster_spec.rb, spec/support/fake_io_reactor.rb, spec/support/stub_io_reactor.rb
* Decrement the next protocol version to try based on the version we used in communication, not based on the current version set in connection_options.
=> Fixed RUBY-161

lib/cassandra/auth/providers/password.rb, spec/cassandra/auth/providers/password_spec.rb
RUBY-169 - Ignore authenticator name when creating password authenticator.
NB: Not updating CHANGELOG because this is so under the hood that I don't think users would notice.
=> RUBY-169 - Ignore authenticator name when creating password authenticator

lib/cassandra/attr_boolean.rb, lib/cassandra/cluster/options.rb, lib/cassandra/column_container.rb, lib/cassandra/errors.rb, lib/cassandra/protocol/cql_protocol_handler.rb, lib/cassandra/protocol/request.rb
Fixed up some more boolean methods to use attr_boolean
=> RUBY-182 - Move attr_boolean to its own module

features/basics/schema_metadata.feature, integration/metadata_test.rb, integration/schema_change_listener.rb
Also includes tests for RUBY-170, RUBY-179, RUBY-180.
=> [RUBY-181] Integration tests and cucumber features for table metadata

CHANGELOG.md, integration/metadata_test.rb, lib/cassandra/cluster/schema/fetchers.rb, spec/cassandra/cluster/schema/fetchers/3.0.0-data.json
* Updated CHANGELOG
* Added integration test.
=> RUBY-186 - Handle custom type columns in C* 3.x schemas.

integration/indexes/indexes_test.rb, integration/indexes/materialized_view_test.rb, integration/schema_change_listener.rb
Removed sleeps and properly skip tests.
=> Bugfixes in indexes tests

lib/cassandra/util.rb, spec/cassandra/table_spec.rb
* Also properly escape names that contain double-quotes.
=> RUBY-175 - escape reserved words

lib/cassandra/column_container.rb, lib/cassandra/keyspace.rb
* Fixed subtle bug in setting the keyspace attribute of a view; it would only be set if the view didn't have a keyspace initially. However,
as schema updates occur, views and tables can transfer from one keyspace to a new version of the keyspace.
=> RUBY-241 - MaterializedView base_table returns nil sometimes

CHANGELOG.md, integration/client_error_test.rb, lib/cassandra.rb, lib/cassandra/cluster/connector.rb, lib/cassandra/cluster/options.rb, lib/cassandra/driver.rb, lib/cassandra/errors.rb, lib/cassandra/protocol.rb, lib/cassandra/protocol/cql_byte_buffer.rb, lib/cassandra/protocol/responses/read_failure_error_response.rb, lib/cassandra/protocol/responses/write_failure_error_response.rb, lib/cassandra/protocol/v4.rb, spec/cassandra/cluster/options_spec.rb, spec/cassandra_spec.rb, support/ccm.rb
* Added allow_beta_protocol option to Cassandra.cluster
* Added handling for v5 versions of read-failure and write-failure responses.
* Added ability to run integration tests against a C* cluster using a locally build C* tree.
=> RUBY-254 - beta protocol support

.gitignore, CONTRIBUTING.md, lib/cassandra/cluster/control_connection.rb, lib/cassandra/executors.rb, lib/cassandra/uuid/generator.rb, spec/spec_helper.rb
We author a gem that has the ruby-driver as a dependency.
These are fixups for a few of the warnings that are are most repeatedly reported when we run our suite.
Happy to hear y'alls thoughts if we're being pedantic here, but we try to run our unit suite with warnings enabled to help fight entropy.
=> fixup a few ruby warnings

Gemfile.lock, lib/cassandra/util.rb, spec/cassandra/util_spec.rb
Fixnum and Bignum classes were unified to a single integer class in Ruby 2.4. All integers in Ruby 2.4 would match to ::Fixnum. For proper type guessing, the size of the number needs to be inspected.
Fixes [RUBY-294](https://datastax-oss.atlassian.net/browse/RUBY-294).
=> Ruby 2.4 compatible integer type guessing

lib/cassandra/session.rb
The custom message on asserting that options are a hash gets invoked on every query execution when options are supplied. This can add up to quite a lot of Hash.inspect calls that don't ever do anything if you use options on your queries.
Since this is just an assertion failure message, I think it would be better to just go with the default message (which is nearly identical) rather than adding the additional overhead.
=> Remove custom message on options assertion

build.yaml
Work in progress, need to make sure everything runs cleanly
=> Use ubuntu/bionic64/ruby-driver bionic image on jenkins

lib/cassandra/cluster/schema/cql_type_parser.rb
Azure CosmosDB's cassandra returns `varchar` as a type for `text` fields.
This commit allows the `CqlTypeParser` to successfully read `varchar` fields as `text`.
=> Add varchar to Cassandra::Types.text mapping
