datastax/ruby-driver

integration/session_test.rb
lib/cassandra/cluster/client.rb
lib/cassandra/protocol/coder.rb
lib/cassandra/protocol/requests/query_request.rb
lib/cassandra/protocol/v1.rb
lib/cassandra/protocol/v3.rb
lib/cassandra/session.rb
lib/cassandra/statements/batch.rb
lib/cassandra/statements/simple.rb

allows named parameters in simple statements

add support for named parameters in simple statements

---

cucumber.yml
features/basics/datatypes.feature
integration/types/datatype_test.rb
integration/types/user_defined_type_test.rb
support/ccm.rb

Tests for nested collections, including integration tests and cucumber features.

[RUBY-94] Tests for nested collections

---

integration/session_test.rb

Test for synchronize_schema disabling.

[RUBY-97] Test for synchronize_schema disabling

---

lib/cassandra/cluster/control_connection.rb
lib/cassandra/cluster/schema.rb

Minor method name typo I came across while digging through the source.

Udpate is not a thing

---

.yardopts
integration/load_balancing/round_robin_test.rb
integration/security/authentication_test.rb
integration/session_test.rb
integration/types/datatype_test.rb

Updated yardopts to include integration test files for doc parsing, and added YARD test doc examples.

 Updated yardopts and added YARD test examples

---

integration/functions/user_defined_function_test.rb
lib/cassandra/cluster/schema/cql_type_parser.rb
lib/cassandra/cluster/schema/fqcn_type_parser.rb
lib/cassandra/function.rb
lib/cassandra/protocol/coder.rb
lib/cassandra/types.rb

Coerce varchar type into text since Cassandra treats varchar's as text's.

Varchar => Text

---

lib/cassandra.rb
lib/cassandra/cluster/connector.rb
lib/cassandra/cluster/options.rb
lib/cassandra/driver.rb
lib/cassandra/protocol/cql_protocol_handler.rb
spec/cassandra/cluster/options_spec.rb
spec/cassandra/protocol/cql_protocol_handler_spec.rb
spec/cassandra_spec.rb

Add connections_per_local_node, connections_per_remote_node, requests_per_connection options.

Fixed RUBY-100

---

lib/cassandra/execution/options.rb

Don't validate execution options that haven't changed during override.

Fixed RUBY-154

---

README.md
features/debugging/execution_info.feature
features/debugging/request_tracing.feature

* Added feature test showing that warnings are captured properly in the driver.
* Fixed broken test
* Updated README copyright and list of supported C* and DSE versions.

Fixed RUBY-133

---

cucumber.yml
support/ccm.rb

Adding DSE support into the integration test suite.

Add DSE support into the test harness

---

docs.yaml

Added url rewrite rules in docs.yaml for tweaking links when generating documentation

Added url rewrite rules in docs.yaml

---

lib/cassandra.rb

PR addressing issue-174https://datastax-oss.atlassian.net/browse/RUBY-174

move cluster options list into Cassandra::CLUSTER_OPTIONS

---

.rubocop.yml
lib/cassandra/attr_boolean.rb
lib/cassandra/cluster/schema/fetchers.rb
lib/cassandra/types.rb
lib/cassandra/udt.rb

* Reformat sample code snippets related to UDT's.
* Change attr_boolean to return true if object is non-nil, rather than returning the object.

RUBY-183 - Run rubocop on fetchers.rb and types.rb

---

integration/client_warnings_test.rb

CASSANDRA-10876 affects C* >= 3.6.

Fix client warning tests (CASSANDRA-10876)

---

Gemfile.lock
lib/cassandra/cluster.rb
lib/cassandra/execution/profile_manager.rb
lib/cassandra/version.rb
spec/support/stub_io_reactor.rb

* Also bump version to 3.1.0.rc.1 in preparation of 3.1.0 release.

RUBY-266 - expose execution profiles through cluster object

---

lib/cassandra/cluster/client.rb

https://datastax-oss.atlassian.net/projects/RUBY/issues/RUBY-292
```
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:436 in connect_to_host_with_retry
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:115 in block (2 levels) in connect
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:114 in each
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:114 in block in connect
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:391 in block in map
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:752 in call_listener
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:791 in block in resolve …
```

RUBY-292 replace failed connections to prevent ip for string errors

---

lib/cassandra/cluster/control_connection.rb
lib/cassandra/cluster/registry.rb
spec/cassandra/cluster/control_connection_spec.rb

* added address resolution calls in various places as appropriate.

RUBY-295 - Custom Address Resolution Feature fails

---

lib/cassandra/protocol/cql_protocol_handler.rb

* Clean-up and refactor based on review comments.

RUBY-316: Fix timer-future leak in Ruby driver

---

lib/cassandra/cluster/schema/cql_type_parser.rb
lib/cassandra/cluster/schema/fqcn_type_parser.rb
lib/cassandra/types.rb
spec/cassandra/cluster/schema/fetchers/2.2.1-data.json
spec/cassandra/cluster/schema/fetchers/2.2.1-schema.cql
spec/cassandra/cluster/schema/fetchers/3.0.0-data.json
spec/cassandra/cluster/schema/fetchers/3.0.0-schema.cql

https://datastax-oss.atlassian.net/browse/RUBY-324

RUBY-324: Handle frozen collections correctly

---

integration/metadata_test.rb
lib/cassandra/table.rb
spec/cassandra/cluster/schema/fetchers/1.2.19-schema.cql
spec/cassandra/cluster/schema/fetchers/2.0.16-schema.cql
spec/cassandra/cluster/schema/fetchers/2.1.9-schema.cql
spec/cassandra/cluster/schema/fetchers/2.2.1-schema.cql
spec/cassandra/cluster/schema/fetchers/3.0.0-schema.cql
spec/cassandra/table_spec.rb

https://datastax-oss.atlassian.net/browse/RUBY-326

RUBY-326: Export also ascending clustering order on tables

---

docs.yaml

Added EOL YAML option to docs.yaml file.

DOC-2089: add YAML option for EOL docs.

---

docs.yaml

Added/combined content:
- search: 'https://(helpdocs|docs).datastax.com/(en/astra/)?(aws|gcp)/(dscloud/apollo|doc/dscloud/astra)/dscloudGettingStarted.html'
replace: 'https://docs.datastax.com/en/astra-serverless/docs/getting-started/getting-started.html'
- search: 'https://(helpdocs|docs).datastax.com/(en/astra/)?(aws|gcp)/(dscloud/apollo|doc/dscloud/astra)/dscloudObtainingCredentials.html'
replace: 'https://docs.datastax.com/en/astra-serverless/docs/connect/secure-connect-bundle.html'
- search: 'https://(helpdocs|docs).datastax.com/(en/astra/)?(aws|gcp)/(dscloud/apollo|doc/dscloud/astra)/dscloudShareClusterDetails.html'
replace: 'https://docs.datastax.com/en/astra-serverless/docs/manage/org/manage-tokens.html'
- search: 'http://downloads.datastax.com/java-driver/'
replace: …

DOC-4040 update to docs.yaml
